### ISSUE TITLE
I can‘t run the example

### ISSUE THREAD

**Issue by iOSstudyPerson** [jjochen/JJFloatingActionButton#256] opened 2020-04-02 07:12 UTC
I want to run the example project, But I failed when I executed the pod update command.
And I don't know how to download this version of public_suffix-2.0.5.
can you help me? Thanks

**Comment by jjochen** [comment] 2020-04-17 18:14
@iOSstudyPerson Did #261 resolve your problem?

**Comment by jjochen** [comment] 2020-04-18 18:05
btw. why did you try to do an `pod update`?

The easies way to run the example is probably by running 
```
pod try JJFloatingActionButton
```

**Comment by jjochen** [comment] 2020-04-18 18:07
I will close this for now. Feel free to reopen it if the issue is not resolved.

**Closed by jjochen** 2020-04-18 18:07 UTC
Labels: support
