### ISSUE TITLE
Action button items are not shown when added to custom button on center tab.

### ISSUE THREAD

**Issue by scubax07** [jjochen/JJFloatingActionButton#265] opened 2020-05-18 05:24 UTC
`        self.tabBar.addSubview(middleBtn)
        middleBtn.addSubview(actionButton)
        actionButton.translatesAutoresizingMaskIntoConstraints = false
        actionButton.centerXAnchor.constraint(equalTo: middleBtn.centerXAnchor).isActive = true
        actionButton.centerYAnchor.constraint(equalTo: middleBtn.centerYAnchor).isActive = true
        self.view.layoutIfNeeded()`

**Comment by jjochen** [comment] 2020-05-21 13:28
This is basically a duplicate of #196. I’ll try to look into it.

**Comment by scubax07** [comment] 2020-05-26 04:59
Thanks man.

**Comment by scubax07** [comment] 2020-05-28 10:51
I was able to get a work around this issue by adding getting the current view controller and adding the view to it with necessary constraints.

`guard let currentView = HelperMethods.getCurrentViewController()?.view else { return }
  currentView.addSubview(actionButton)`

**Closed** 2020-05-28 10:52 UTC
Labels: bug

**Comment by jarrillaga** [comment] 2020-06-15 21:24
@scubax07 Hey ! Can you share your code of how you solve this? I'm trying to add the button in the middle of the tabbar and I could, but the actions doesn't work and I think that you have fixed it.

**Comment by scubax07** [comment] 2020-06-16 09:26
> @scubax07 Hey ! Can you share your code of how you solve this? I'm trying to add the button in the middle of the tabbar and I could, but the actions doesn't work and I think that you have fixed it.

Hi, I added the FAB button to the root controller with necessary constraints.

`       let appDelWin = UIApplication.shared.windows.first
        
        guard let currentView = appDelWin?.rootViewController?.view else { return }
        
        currentView.addSubview(actionButton)
        
        actionButton.translatesAutoresizingMaskIntoConstraints = false
        actionButton.centerXAnchor.constraint(equalTo: currentView.centerXAnchor).isActive = true
        actionButton.bottomAnchor.constraint(equalTo: currentView.bottomAnchor, constant: -50).isActive = true `

I did this in my main tab controller class.
Also don't forget to hide/unhide when you switch controllers as per your need.
Hope this helps.
