### ISSUE TITLE
How do I show only one Action Item?

### ISSUE THREAD

**Issue by nkmhang** [jjochen/JJFloatingActionButton#208] opened 2019-08-30 08:30 UTC
It seems my only one Action Item replace with Action Button. It does not show as I expect.
I expect my only one Action Item should be floating too

**Comment by jjochen** [comment] 2019-08-30 08:49
You can use `handleSingleActionDirectly`.
Apparently I need to add better documentation for this. 
Duplicate of #202

**Closed** 2019-09-09 13:20 UTC
Labels: support
