### ISSUE TITLE
IB Designables: required code signature missing?

### ISSUE THREAD

**Issue by Swisyn** [jjochen/JJFloatingActionButton#142] opened 2018-04-30 17:14 UTC
Hello, 

i was trying to add that view to storyboard and facing with that weird problem. Any solutions for this issue? 

/Base.lproj/Main.storyboard: error: IB Designables: Failed to render and update auto layout status for PResultsViewController (waN-Mo-Hrd): dlopen(JJFloatingActionButton.framework, 1): no suitable image found.  Did find: JJFloatingActionButton.framework: required code signature missing for 'JJFloatingActionButton.framework'

**Comment by jjochen** [comment] 2018-05-02 08:02
Apparently there is an [issue](https://github.com/CocoaPods/CocoaPods/issues/7606) with cocoapods 1.5. Is this the version you are using?

You could try to use [this workaround](https://github.com/CocoaPods/CocoaPods/issues/7606#issuecomment-381279098) or downgrade to cocoapods 1.4

**Comment by Swisyn** [comment] 2018-05-02 13:44
Thank you so much for the quick response. I had searched the issue on web but couldn't find anything that's why i opened the issue and didn't even think issue is related to cocoapods.

this code solved the issue after i added it to pod file.
`# Workaround for Cocoapods issue #7606
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end`

**Comment by jjochen** [comment] 2018-05-02 13:48
Good to hear  👍

**Comment by wdcurry** [comment] 2018-05-07 11:59
This issue is found in the demo project as well, does it exist within the pre-cocoapods code itself? I prefer not to adjust my overall build settings for this one issue as it only appears after adding this pod, thanks kindly.

Again, awesome repo!

**Comment by jjochen** [comment] 2018-05-07 13:28
@wdcurry I'm not sure what you mean with "pre-cocoapods code". 
And weirdly enough, I couldn't reproduce this issue with the demo project. Hmm...

But as far as I can tell it's not something I can fix anyway, as it has nothing to do with the library but the way CocoaPods handles `@IBDesignable` frameworks (see [here](https://github.com/CocoaPods/CocoaPods/issues/7606)).

As far as I know the only things you can do right now are 
* add the button programmatically, 
* downgrade to an older version of CocoaPods, where this issue doesn't exist (1.4), 
* or use [this workaround](https://github.com/CocoaPods/CocoaPods/issues/7606#issuecomment-381279098).

**Comment by wdcurry** [comment] 2018-05-10 20:35
I mean simply the project as it functions at your end prior to the inclusion into the cocoa pod ecosystem. I guess that is a moot question now, given your explanation that this seems to be a pods issue. I just wonder what it is about this repo that causes the issue when none of the others that i use exhibit this issue?

**Comment by jjochen** [comment] 2019-03-31 19:27
Should be fixed with cocoapods 1.6. If not, feel free to reopen the issue.

**Closed by jjochen** 2019-03-31 19:27 UTC
Labels: bug, support
